#
# PSMQTT configuration file
# All values shown here are the default values
#

logging:
  level: DEBUG

  # psmqtt will report its own status (e.g. number of errors) every N seconds on its log output
  # and on the specific '<mqtt.publish_topic_prefix>/status' topic
  report_status_period_sec: 10

mqtt:
  # broker: details about the MQTT broker
  broker:
    host: mqtt.flespi.io
    port: 8883
    username: 't0YN9MIfPj0OzYr3TpEkqEFlDhvkHI5ZwSAvu8A7ipJFd1wUg04uuzEWGZ6cx0ZS'
    password: ''
  
  # client_id: the identifier of the MQTT client created by psmqtt; this is useful to identify psmqtt
  # when inspecting the MQTT broker logs
  clientid: psmqtt-sonnaz-server
  
  # clean_session: If "true", the broker will remove all information about this client when it disconnects. 
  # If "false", the client is a persistent client and subscription information and queued messages will 
  # be retained when the client disconnects
  clean_session: true
  
  # qos: it can be:
  #  - At most once (QoS 0)
  #  - At least once (QoS 1)
  #  - Exactly once (QoS 2)
  # see https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/
  qos: 1
  
  # retain: if set to true, the message will be set as the "last known good"/retained message for 
  # each topic populated by psmqtt
  retain: false

  # reconnect_period_sec: defines how frequently psmqtt will re-attempt a connection to the MQTT broker
  # if the connection is lost. You should be setting this parameter to the smallest value that makes sense
  # according to your PSMQTT scheduling rules.
  reconnect_period_sec: 5

  # request: name of the topic that psmqtt will subscribe to, and where it will wait for information requests;
  # to activate the request just send any payload message (e.g. "REQUEST") to a topic like:
  # <psmqtt/COMPUTER_NAME/request/cpu_percent>. 
  request_topic: "psmqtt_test/sonnaz-server/request/"

  # publish_topic_prefix: defines the prefix for all published topics;
  # if not provided, it defaults to "psmqtt/<hostname>/"
  publish_topic_prefix: "psmqtt/sonnaz-server/"

  ha_discovery:
    enabled: false

    
options:
  # exit_after_num_tasks: this configuration parameter is used to simulate the "psmqtt-publish.py" script variant that was
  # provided in the past by psmqtt project; if exit_after_num_tasks=N, psmqtt will gracefully exit after
  # publishing all data associated with N tasks, that are executed according to usual scheduling rules.
  # The special value ZERO indicates that psmqtt publish tasks indefinitively, until stopped via SIGTERM.
  exit_after_num_tasks: 0

schedule:
  # Each scheduling rule is defined by a cron expression and a list of tasks to be executed;
  # the "cron" expression is a human-friendly expression, see https://github.com/kvh/recurrent/tree/master
  # for example of supported syntaxes
  - cron: "every 1 minute"
    tasks:  
      # Each task is defined by
      # * "task": the name (see PSMQTT docs for full list of available task handlers);
      # * "params": optional task parameters (e.g. percentage or absolute value, the name of an hard drive or the index of a CPU, etc);
      # * "topic": optional MQTT topic name; if this is not provided, the task name and all its parameters will be used as MQTT topic;
      # * "formatter": optional formatter expression, which is a Jinja2 expression
      # see "Usage docs" for more details
      - task: cpu_percent
        params: [ total ]
        topic: cpu_percent
      - task: virtual_memory
        params: [ percent ]
        topic: mem_percent
      - task: getloadavg
        params: [ "last5min", "percent" ]
        formatter: "{{'%0.2f'|format(x)}}"

#   - cron: "every 10 minutes"
#     tasks:
      - task: sensors_temperatures
        params: [ coretemp, * ]
        topic: temp
      - task: disk_usage
        params: [ percent , "/" ]
        topic: du_root_percent

#   - cron: "every 60 minutes"
#     tasks:
      - task: boot_time
        params: [ uptime ]
        topic: uptimesec
      - task: boot_time
        params: [ uptimesec ]
        topic: uptimesec
